### ISSUE TITLE
質問3 実装内容について

### ISSUE THREAD

**Issue by Mulyu** [access-company/AutoWeb-Hackathon#3]
Webアプリケーションに対するインターフェースをネイティブアプリとして実装するのは不可でしょうか？

**Comment by aShinjiroUrata** [comment]
すみません、もう少し具体的なお話を聞きたいのですが、どちらのグループの方でしょうか？

**Comment by hoshitocat** [comment]
Eグループです :octocat:

**Comment by aShinjiroUrata** [comment]
「Ｗｅbアプリケーションだけでなく、スマホ連携のためにiPhone/Androidアプリを作成してシステムに含めて構わないか」というご質問でした。
そのあたりはとくに制限はありませんので、自由に創造性を発揮してください。

**Comment by Mulyu** [comment]
ありがとうございました
