### ISSUE TITLE
午前中の解説スライドに関して

### ISSUE THREAD

**Issue by Mulyu** [access-company/AutoWeb-Hackathon#4]
評価基準などを記述した午前中の解説スライドに関して、後ほどアップロードするとのことでしたが、
どこにアップロードされているか教えていただけないでしょうか。

**Comment by aShinjiroUrata** [comment]
以下にpdf形式で配置しましたのでご参照ください。

https://github.com/access-company/AutoWeb-Hackathon/blob/master/doc/files/hackathon_guidance.pdf

**Comment by Mulyu** [comment]
ありがとうございました。
