### ISSUE TITLE
車両情報の生データ取得方法はありますか

### ISSUE THREAD

**Issue by aKosukeNagano** [access-company/AutoWeb-Hackathon#7]
緯度経度の情報から動画の位置を逆引きしたい

**Comment by aKosukeNagano** [comment]
[MapTool](http://52.193.125.145:3000/MapTool/osm_mapping.html) では[Vehicle API システム構成図](https://github.com/access-company/AutoWeb-Hackathon) のJSONファイルを直接読み込んでいます。

InspectorからConsoleのログを見ていると、どういうリクエストを出しているかが見えますので確認してみてください。

**Comment by aShinjiroUrata** [comment]
前記のJSONファイルと呼んでいるものは、作成時の都合のため一部不完全な形式になっています。
具体的には、
  {...},{...},{...},{...}
となっており、JavaScriptの JSON.parse()や一般のJSON整形ツールではエラーになります。

JSONとして正しい形式にするには
先頭と末尾に [ ] を付加して
 [ {...},{...},{...},{...} ]
という形にすることが必要です。

**Comment by aShinjiroUrata** [comment]
以下のようにして直接取得できます。
wget http://52.193.125.145:3000/MapTool/json/201601072213_kasumigaseki_sangenjyaya.json
