### ISSUE TITLE
Accelerationの単位と正負について

### ISSUE THREAD

**Issue by kafumi** [access-company/AutoWeb-Hackathon#8]
Iチームの神田です。Accelerationにて取得できる加速度に関して質問させてください。

Accelerationの単位
---
[Vehicle Data](https://www.w3.org/2014/automotive/data_spec.html) の定義を見ると、Accelerationの各プロパティ値の単位は "centimeters per second squared" = cm/s^2 と説明されています。つまり、標準重力加速度が約980.0で、0.1Gは98.0程度になると思ったのですが、取得できる値を見ると、大半が0.1未満に収まっているようです。取得できる値の単位は何になっていますでしょうか。m/s^2としても小さすぎる気がするので、もしかしたら標準重力加速度に対する比率でしょうか。

Accelerationのプロパティ値の正負
---

前後方向の加速度を表すAcceleration.yは、加速・減速のどちらが負値に対応するでしょうか。
READMEで説明されている座標系を見ると、Y軸の正方向は車両前方向なので、加速が負、減速が正となるかと思ったのですが、現在、配信されている車両データを見ると、加速が正、減速が負になっているようです。どちらが正しいでしょうか。

**Comment by aShinjiroUrata** [comment]
説明が不足し失礼しました。
・機器の都合からAccelerationの単位はＷ３Ｃの仕様と違えており、Gが正しいです。

・前後方向加速度
　・ご指摘の通り、加速が正、減速が負、となっております。　したがってＲＥＡＤＭＥの図が間違っているとお考えください。

**Comment by kafumi** [comment]
ご回答ありがとうございます。理解しました。
